// Package domain defines invite-code registration and session types.
package domain

import (
	"errors"
	"time"
)

// InviteCodeState is the lifecycle of a registration invite code.
type InviteCodeState string

const (
	InviteCodeActive  InviteCodeState = "active"
	InviteCodeUsed    InviteCodeState = "used"
	InviteCodeRevoked InviteCodeState = "revoked"
	InviteCodeExpired InviteCodeState = "expired"
)

// InviteCode is a one-time registration credential generated by an admin.
type InviteCode struct {
	Code            string
	CreatedByUserID int64
	UsedByUserID    *int64
	UsedAt          *time.Time
	ExpiresAt       time.Time
	State           InviteCodeState
	CreatedAt       time.Time
}

// IsConsumable reports whether the invite code can still be used to register.
func (ic InviteCode) IsConsumable(now time.Time) bool {
	return ic.State == InviteCodeActive && now.Before(ic.ExpiresAt)
}

// UserSession is a bearer token issued to an authenticated user after
// registration or login.
type UserSession struct {
	TokenHash string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

// invite 域业务哨兵(错误域分类, 见 docs/FAILURE_POLICY.zh-CN.md)。
// ErrInviteCodeInvalid 已定义于 team.go(注册/团队邀请共用), 此处补充
// revoke 路径哨兵。
var ErrInviteNotFound = errors.New("invite code not found or not active")
