// Package domain defines invite-code registration and session types.
package domain

import "time"

// InviteCodeState is the lifecycle of a registration invite code.
type InviteCodeState string

const (
	InviteCodeActive  InviteCodeState = "active"
	InviteCodeUsed    InviteCodeState = "used"
	InviteCodeRevoked InviteCodeState = "revoked"
	InviteCodeExpired InviteCodeState = "expired"
)


// InviteCode is a one-time registration credential generated by an admin.
type InviteCode struct {
	Code           string
	CreatedByUserID int64
	UsedByUserID   *int64
	UsedAt         *time.Time
	ExpiresAt      time.Time
	State          InviteCodeState
	CreatedAt      time.Time
}

// IsConsumable reports whether the invite code can still be used to register.
func (ic InviteCode) IsConsumable(now time.Time) bool {
	return ic.State == InviteCodeActive && now.Before(ic.ExpiresAt)
}

// UserSession is a bearer token issued to an authenticated user after
// registration or login.
type UserSession struct {
	TokenHash string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}
