# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from genericagent.worker.v1 import worker_pb2 as genericagent_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in genericagent/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/genericagent.worker.v1.WorkerService/StartSession',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.ReloadCredentials = channel.unary_unary(
                '/genericagent.worker.v1.WorkerService/ReloadCredentials',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ReloadCredentialsRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ReloadCredentialsResponse.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_stream(
                '/genericagent.worker.v1.WorkerService/ExecuteTask',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
                _registered_method=True)
        self.BeginCheckpoint = channel.unary_unary(
                '/genericagent.worker.v1.WorkerService/BeginCheckpoint',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.BeginCheckpointRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.CheckpointReady.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/genericagent.worker.v1.WorkerService/CancelTask',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/genericagent.worker.v1.WorkerService/Health',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/genericagent.worker.v1.WorkerService/Shutdown',
                request_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.StartSessionRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.StartSessionResponse.SerializeToString,
            ),
            'ReloadCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadCredentials,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ReloadCredentialsRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ReloadCredentialsResponse.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.WorkerEvent.SerializeToString,
            ),
            'BeginCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginCheckpoint,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.BeginCheckpointRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.CheckpointReady.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.CancelTaskRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.CancelTaskResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ShutdownRequest.FromString,
                    response_serializer=genericagent_dot_worker_dot_v1_dot_worker__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genericagent.worker.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genericagent.worker.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/StartSession',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.StartSessionRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/ReloadCredentials',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.ReloadCredentialsRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.ReloadCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/ExecuteTask',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.ExecuteTaskRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/BeginCheckpoint',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.BeginCheckpointRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.CheckpointReady.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/CancelTask',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.CancelTaskRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/Health',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genericagent.worker.v1.WorkerService/Shutdown',
            genericagent_dot_worker_dot_v1_dot_worker__pb2.ShutdownRequest.SerializeToString,
            genericagent_dot_worker_dot_v1_dot_worker__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
