"""Security audit: prove the real upstream LLM key never reaches the Worker.

Static analysis of Go + Python source verifying the spec §7.1 red line:
"平台真实 LLM Key 永不进入 Worker." The real upstream key
(``LLM_PROXY_UPSTREAM_APIKEY``) lives ONLY in the LLM Proxy's Forwarder; the
Worker receives a short-lived capability_token + Proxy URL via a token-only
``mykey.py`` generated by the scheduler.

These checks are static (no DB, no process startup) so they run on every host.
End-to-end runtime verification (grepping Worker process env + generated files
at runtime) is covered by the full suite in Step 8 with a real DB.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_GO = REPO_ROOT / "tenant_platform" / "backend-go"

# The real upstream key env var + Go field names. These MUST NOT appear in any
# code that constructs the Worker process environment or writes mykey.py.
REAL_KEY_ENV_VAR = "LLM_PROXY_UPSTREAM_APIKEY"
REAL_KEY_GO_FIELDS = ("UpstreamAPIKey", "upstreamAPIKey", "upstreamApiKey")
# Legacy OAI fixture code that was removed in Slice 2a (security red line).
LEGACY_REMOVED = ("writeFixtureMyKey", "startOAIFixture", "oaiFixture", "testToken", "OAIBaseURL")


def _read(relative_path: str) -> str:
    path = BACKEND_GO / relative_path
    assert path.is_file(), f"missing Go source: {path}"
    return path.read_text(encoding="utf-8")


def _read_python(relative_path: str) -> str:
    path = REPO_ROOT / relative_path
    assert path.is_file(), f"missing Python source: {path}"
    return path.read_text(encoding="utf-8")


def test_scheduler_has_no_real_key_reference() -> None:
    """scheduler.go must not reference the real key env var or Go field names."""
    src = _read("internal/application/scheduler.go")
    assert REAL_KEY_ENV_VAR not in src, "scheduler.go references real key env var"
    for field in REAL_KEY_GO_FIELDS:
        assert field not in src, f"scheduler.go references real key field: {field}"


def test_worker_credential_has_no_real_key_reference() -> None:
    """worker_credential.go writes only token + Proxy URL, never the real key."""
    src = _read("internal/application/worker_credential.go")
    assert REAL_KEY_ENV_VAR not in src, "worker_credential.go references real key env var"
    for field in REAL_KEY_GO_FIELDS:
        assert field not in src, f"worker_credential.go references real key field: {field}"
    # The template must use the token param, not a real key.
    assert "token" in src, "worker_credential.go must use the token param"
    assert "proxyAddr" in src or "proxy_addr" in src, "worker_credential.go must use the proxy addr param"


def test_scheduler_requires_token_issuer_when_dial_worker_nil() -> None:
    """NewScheduler must reject construction without TokenIssuer for real Worker path."""
    src = _read("internal/application/scheduler.go")
    assert "TokenIssuer" in src, "scheduler must reference TokenIssuer"
    assert "DialWorker" in src, "scheduler must reference DialWorker"
    assert "TokenIssuer is required" in src, "scheduler must enforce TokenIssuer requirement"
    assert "DialWorker is nil" in src, "scheduler must gate on DialWorker nil"


def test_no_legacy_oai_fixture_code_remains() -> None:
    """Legacy OAI fixture code must be fully removed from scheduler.go."""
    src = _read("internal/application/scheduler.go")
    for legacy in LEGACY_REMOVED:
        assert legacy not in src, f"legacy OAI fixture code remains in scheduler.go: {legacy}"


def test_real_key_only_in_llmproxy_package() -> None:
    """The real key Go field may appear ONLY in internal/llmproxy/, not in application/."""
    application_files = [
        f for f in (BACKEND_GO / "internal" / "application").glob("*.go")
        if not f.name.endswith("_test.go")
    ]
    assert application_files, "expected application package Go files"
    for path in application_files:
        src = path.read_text(encoding="utf-8")
        for field in REAL_KEY_GO_FIELDS:
            assert field not in src, f"{path.name} references real key field: {field}"


def test_forwarder_never_logs_api_key() -> None:
    """The Forwarder must never log the apiKey field — only status/URL/byte count."""
    src = _read("internal/llmproxy/upstream.go")
    assert "Authorization" in src, "forwarder must set Authorization header"
    assert "Bearer" in src, "forwarder must use Bearer auth"
    # Check actual log OUTPUT calls (Printf) for apiKey leakage. Struct
    # construction like `log: log.Default()` is not a log output call.
    for line in src.splitlines():
        stripped = line.strip()
        if "Printf" in stripped:
            assert "apiKey" not in stripped, f"forwarder log may leak key: {stripped}"
            assert "ApiKey" not in stripped, f"forwarder log may leak key: {stripped}"


def test_handler_validates_token_before_forwarding() -> None:
    """The Proxy handler must validate the capability_token before calling Forward."""
    src = _read("internal/llmproxy/handler.go")
    assert "Validate" in src or "validator" in src, "handler must validate token"
    assert "Forward" in src or "forward" in src, "handler must forward validated request"
    # The handler must not reference the real key field.
    for field in REAL_KEY_GO_FIELDS:
        assert field not in src, f"handler.go references real key field: {field}"


def test_smoke_does_not_write_real_key_to_mykey_py() -> None:
    """foundation_smoke.py must not write OAI_TOKEN into mykey.py directly."""
    src = _read_python("tenant_platform/tests/smoke/foundation_smoke.py")
    # The legacy _write_fixture_config function must be removed.
    assert "_write_fixture_config" not in src, "smoke still has _write_fixture_config"
    # OAI_TOKEN must only appear in LLM_PROXY_UPSTREAM_APIKEY assignment, not in
    # any mykey.py file-write content.
    assert "LLM_PROXY_UPSTREAM_APIKEY" in src, "smoke must pass key via env var"
    # No line may both reference mykey.py AND perform a write/open operation.
    _assert_no_write_to_mykey_py(src, "foundation_smoke.py")


def test_integration_passes_key_via_env_not_mykey_py() -> None:
    """test_foundation_flow.py must pass OAI_TOKEN via env, not via mykey.py."""
    src = _read_python("tenant_platform/tests/integration/test_foundation_flow.py")
    assert "LLM_PROXY_UPSTREAM_APIKEY" in src, "integration must pass key via env var"
    _assert_no_write_to_mykey_py(src, "test_foundation_flow.py")


def _assert_no_write_to_mykey_py(src: str, label: str) -> None:
    """Assert no line both references mykey.py and performs a file-write operation."""
    write_markers = ("write_text", "write(", "open(", "WriteFile", "chmod")
    for line in src.splitlines():
        if "mykey.py" in line:
            for marker in write_markers:
                assert marker not in line, f"{label} writes mykey.py directly: {line.strip()}"


def test_llmcore_does_not_reference_real_key_env() -> None:
    """llmcore.py (frozen) must not reference LLM_PROXY_UPSTREAM_APIKEY."""
    src = _read_python("llmcore.py")
    assert REAL_KEY_ENV_VAR not in src, "llmcore.py references real key env var"
