# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genericagent/proxy/v1/llm_proxy.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'genericagent/proxy/v1/llm_proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%genericagent/proxy/v1/llm_proxy.proto\x12\x15genericagent.proxy.v1\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x85\x01\n\x0fGenerateRequest\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\x12\x18\n\x10\x63\x61pability_token\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x34\n\x08messages\x18\x04 \x03(\x0b\x32\".genericagent.proxy.v1.ChatMessage\"\x19\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"4\n\x05Usage\x12\x14\n\x0cinput_tokens\x18\x01 \x01(\x03\x12\x15\n\routput_tokens\x18\x02 \x01(\x03\"E\n\rErrorEnvelope\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\"\xb2\x01\n\rGenerateEvent\x12\x30\n\x04text\x18\x01 \x01(\x0b\x32 .genericagent.proxy.v1.TextChunkH\x00\x12-\n\x05usage\x18\x02 \x01(\x0b\x32\x1c.genericagent.proxy.v1.UsageH\x00\x12\x35\n\x05\x65rror\x18\x03 \x01(\x0b\x32$.genericagent.proxy.v1.ErrorEnvelopeH\x00\x42\t\n\x07payload2m\n\x0fLlmProxyService\x12Z\n\x08Generate\x12&.genericagent.proxy.v1.GenerateRequest\x1a$.genericagent.proxy.v1.GenerateEvent0\x01\x42ZZXgithub.com/Imzl-zl/GenericAgent/tenant_platform/backend-go/internal/gen/proxy/v1;proxyv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genericagent.proxy.v1.llm_proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZXgithub.com/Imzl-zl/GenericAgent/tenant_platform/backend-go/internal/gen/proxy/v1;proxyv1'
  _globals['_CHATMESSAGE']._serialized_start=64
  _globals['_CHATMESSAGE']._serialized_end=108
  _globals['_GENERATEREQUEST']._serialized_start=111
  _globals['_GENERATEREQUEST']._serialized_end=244
  _globals['_TEXTCHUNK']._serialized_start=246
  _globals['_TEXTCHUNK']._serialized_end=271
  _globals['_USAGE']._serialized_start=273
  _globals['_USAGE']._serialized_end=325
  _globals['_ERRORENVELOPE']._serialized_start=327
  _globals['_ERRORENVELOPE']._serialized_end=396
  _globals['_GENERATEEVENT']._serialized_start=399
  _globals['_GENERATEEVENT']._serialized_end=577
  _globals['_LLMPROXYSERVICE']._serialized_start=579
  _globals['_LLMPROXYSERVICE']._serialized_end=688
# @@protoc_insertion_point(module_scope)
