package api

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/Imzl-zl/GenericAgent/tenant_platform/backend-go/internal/domain"
)

// GenerateMykeyPy 根据 Provider 列表生成 GA Core 的 mykey.py 配置文件内容
func GenerateMykeyPy(providers []domain.LLMProvider, cipher Cipher) (string, error) {
	var sb strings.Builder

	// 文件头部注释
	sb.WriteString("# Auto-generated by GenericAgent Tenant Platform\n")
	sb.WriteString("# DO NOT EDIT MANUALLY - Changes will be overwritten\n\n")

	// 1. 生成 mixin_config（故障转移配置）
	llmNames := make([]string, 0, len(providers))
	for _, p := range providers {
		if p.State == "active" {
			llmNames = append(llmNames, fmt.Sprintf("'%s'", p.Name))
		}
	}

	sb.WriteString("# Mixin configuration for failover\n")
	sb.WriteString("mixin_config = {\n")
	sb.WriteString(fmt.Sprintf("    'llm_nos': [%s],\n", strings.Join(llmNames, ", ")))
	sb.WriteString("    'max_retries': 10,\n")
	sb.WriteString("}\n\n")

	// 2. 为每个 Provider 生成配置
	for i, p := range providers {
		if p.State != "active" {
			continue
		}

		// 解密 API Key
		keyVersion, err := strconv.Atoi(p.APIKeyKeyVersion)
		if err != nil {
			return "", fmt.Errorf("invalid key version for provider %s: %w", p.Name, err)
		}
		apiKey, err := cipher.Decrypt(p.APIKeyCiphertext, keyVersion)
		if err != nil {
			return "", fmt.Errorf("decrypt api key for provider %s: %w", p.Name, err)
		}

		// 配置变量名
		varName := fmt.Sprintf("native_%s_config_%d",
			strings.ReplaceAll(string(p.ProviderType), "native_", ""), i)

		sb.WriteString(fmt.Sprintf("# Provider: %s (Type: %s)\n", p.Name, p.ProviderType))
		sb.WriteString(fmt.Sprintf("%s = {\n", varName))
		sb.WriteString(fmt.Sprintf("    'name': '%s',\n", p.Name))
		sb.WriteString(fmt.Sprintf("    'apikey': '%s',\n", string(apiKey)))
		sb.WriteString(fmt.Sprintf("    'apibase': '%s',\n", p.BaseURL))
		sb.WriteString(fmt.Sprintf("    'model': '%s',\n", p.Model))

		cfg := p.SessionConfig
		writeMyKeyString(&sb, "thinking_type", cfg.ThinkingType)
		writeMyKeyInt(&sb, "thinking_budget_tokens", cfg.ThinkingBudgetTokens)
		writeMyKeyString(&sb, "reasoning_effort", cfg.ReasoningEffort)
		writeMyKeyFloat(&sb, "temperature", cfg.Temperature)
		writeMyKeyInt(&sb, "max_tokens", cfg.MaxTokens)
		writeMyKeyInt(&sb, "context_win", cfg.ContextWin)
		writeMyKeyInt(&sb, "trim_keep_prefix", cfg.TrimKeepPrefix)
		writeMyKeyInt(&sb, "max_retries", cfg.MaxRetries)
		writeMyKeyInt(&sb, "read_timeout", cfg.ReadTimeout)
		writeMyKeyBool(&sb, "stream", cfg.Stream)
		writeMyKeyString(&sb, "api_mode", cfg.APIMode)
		writeMyKeyBool(&sb, "fake_cc_system_prompt", cfg.FakeCCSystemPrompt)
		writeMyKeyString(&sb, "user_agent", cfg.UserAgent)
		writeMyKeyString(&sb, "service_tier", cfg.ServiceTier)
		writeMyKeyBool(&sb, "omit_thinking", cfg.OmitThinking)
		writeMyKeyString(&sb, "extra_sys_prompt", cfg.ExtraSysPrompt)

		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func writeMyKeyString(sb *strings.Builder, key string, value *string) {
	if value != nil {
		sb.WriteString(fmt.Sprintf("    '%s': %q,\n", key, *value))
	}
}

func writeMyKeyInt(sb *strings.Builder, key string, value *int) {
	if value != nil {
		sb.WriteString(fmt.Sprintf("    '%s': %d,\n", key, *value))
	}
}

func writeMyKeyFloat(sb *strings.Builder, key string, value *float64) {
	if value != nil {
		sb.WriteString(fmt.Sprintf("    '%s': %g,\n", key, *value))
	}
}

func writeMyKeyBool(sb *strings.Builder, key string, value *bool) {
	if value == nil {
		return
	}
	pythonValue := "False"
	if *value {
		pythonValue = "True"
	}
	sb.WriteString(fmt.Sprintf("    '%s': %s,\n", key, pythonValue))
}
