package api

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/Imzl-zl/GenericAgent/tenant_platform/backend-go/internal/domain"
)

// GenerateMykeyPy 根据 Provider 列表生成 GA Core 的 mykey.py 配置文件内容
func GenerateMykeyPy(providers []domain.LLMProvider, cipher Cipher) (string, error) {
	var sb strings.Builder

	// 文件头部注释
	sb.WriteString("# Auto-generated by GenericAgent Tenant Platform\n")
	sb.WriteString("# DO NOT EDIT MANUALLY - Changes will be overwritten\n\n")

	// 1. 生成 mixin_config（故障转移配置）
	llmNames := make([]string, 0, len(providers))
	for _, p := range providers {
		if p.State == "active" {
			llmNames = append(llmNames, fmt.Sprintf("'%s'", p.Name))
		}
	}

	sb.WriteString("# Mixin configuration for failover\n")
	sb.WriteString("mixin_config = {\n")
	sb.WriteString(fmt.Sprintf("    'llm_nos': [%s],\n", strings.Join(llmNames, ", ")))
	sb.WriteString("    'max_retries': 10,\n")
	sb.WriteString("}\n\n")

	// 2. 为每个 Provider 生成配置
	for i, p := range providers {
		if p.State != "active" {
			continue
		}

		// 解密 API Key
		keyVersion, err := strconv.Atoi(p.APIKeyKeyVersion)
		if err != nil {
			return "", fmt.Errorf("invalid key version for provider %s: %w", p.Name, err)
		}
		apiKey, err := cipher.Decrypt(p.APIKeyCiphertext, keyVersion)
		if err != nil {
			return "", fmt.Errorf("decrypt api key for provider %s: %w", p.Name, err)
		}

		// 配置变量名
		varName := fmt.Sprintf("native_%s_config_%d",
			strings.ReplaceAll(string(p.ProviderType), "native_", ""), i)

		sb.WriteString(fmt.Sprintf("# Provider: %s (Type: %s)\n", p.Name, p.ProviderType))
		sb.WriteString(fmt.Sprintf("%s = {\n", varName))
		sb.WriteString(fmt.Sprintf("    'name': '%s',\n", p.Name))
		sb.WriteString(fmt.Sprintf("    'type': '%s',\n", p.ProviderType))
		sb.WriteString(fmt.Sprintf("    'apikey': '%s',\n", string(apiKey)))
		sb.WriteString(fmt.Sprintf("    'apibase': '%s',\n", p.BaseURL))
		sb.WriteString(fmt.Sprintf("    'model': '%s',\n", p.Model))

		// 添加 config 中的其他字段
		if p.Config.ThinkingType != "" {
			sb.WriteString(fmt.Sprintf("    'thinking_type': '%s',\n", p.Config.ThinkingType))
		}
		if p.Config.MaxTokens > 0 {
			sb.WriteString(fmt.Sprintf("    'max_tokens': %d,\n", p.Config.MaxTokens))
		}
		if p.Config.Temperature > 0 {
			sb.WriteString(fmt.Sprintf("    'temperature': %.2f,\n", p.Config.Temperature))
		}
		if p.Config.MaxRetries > 0 {
			sb.WriteString(fmt.Sprintf("    'max_retries': %d,\n", p.Config.MaxRetries))
		}

		// 新增字段：推理与思考
		if p.Config.ThinkingBudgetTokens > 0 {
			sb.WriteString(fmt.Sprintf("    'thinking_budget_tokens': %d,\n", p.Config.ThinkingBudgetTokens))
		}
		if p.Config.ReasoningEffort != "" {
			sb.WriteString(fmt.Sprintf("    'reasoning_effort': '%s',\n", p.Config.ReasoningEffort))
		}

		// 新增字段：容量与超时
		if p.Config.ContextWin > 0 {
			sb.WriteString(fmt.Sprintf("    'context_win': %d,\n", p.Config.ContextWin))
		}
		if p.Config.ConnectTimeout > 0 {
			sb.WriteString(fmt.Sprintf("    'connect_timeout': %d,\n", p.Config.ConnectTimeout))
		}
		if p.Config.ReadTimeout > 0 {
			sb.WriteString(fmt.Sprintf("    'read_timeout': %d,\n", p.Config.ReadTimeout))
		}

		// 新增字段：传输
		if p.Config.Stream != nil {
			sb.WriteString(fmt.Sprintf("    'stream': %t,\n", *p.Config.Stream))
		}
		if p.Config.APIMode != "" {
			sb.WriteString(fmt.Sprintf("    'api_mode': '%s',\n", p.Config.APIMode))
		}

		// 新增字段：Claude 专属
		if p.Config.FakeCCSystemPrompt != nil {
			sb.WriteString(fmt.Sprintf("    'fake_cc_system_prompt': %t,\n", *p.Config.FakeCCSystemPrompt))
		}
		if p.Config.UserAgent != "" {
			sb.WriteString(fmt.Sprintf("    'user_agent': '%s',\n", p.Config.UserAgent))
		}

		// 新增字段：网络
		if p.Config.Proxy != "" {
			sb.WriteString(fmt.Sprintf("    'proxy': '%s',\n", p.Config.Proxy))
		}

		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}
