-- Slice for invite-code registration, user-scoped sessions, self-service iLink bot binding,
-- and a public/private persona store (built-in + user-created + admin-moderated).

CREATE TABLE IF NOT EXISTS migration_0009_marker ();

-- One-time invite codes generated by admins; consumed on registration.
CREATE TABLE IF NOT EXISTS invite_codes (
    code                TEXT PRIMARY KEY,
    created_by_user_id  BIGINT NOT NULL REFERENCES users (id),
    used_by_user_id     BIGINT REFERENCES users (id),
    used_at             TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ NOT NULL,
    state               TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT invite_codes_state_check CHECK (state IN ('active', 'used', 'revoked', 'expired'))
);

CREATE INDEX IF NOT EXISTS invite_codes_state_idx ON invite_codes (state);
CREATE INDEX IF NOT EXISTS invite_codes_created_by_idx ON invite_codes (created_by_user_id);

-- User bearer sessions returned by register/login.
CREATE TABLE IF NOT EXISTS user_sessions (
    token_hash   TEXT PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at   TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now()))
);

CREATE INDEX IF NOT EXISTS user_sessions_user_idx ON user_sessions (user_id);
CREATE INDEX IF NOT EXISTS user_sessions_expires_idx ON user_sessions (expires_at);

-- Persona store: built-in + private + pending public + approved public.
CREATE TABLE IF NOT EXISTS personas (
    id              UUID PRIMARY KEY,
    author_user_id  BIGINT NOT NULL REFERENCES users (id),
    name            TEXT NOT NULL,
    description     TEXT,
    system_prompt   TEXT NOT NULL,
    is_public       BOOLEAN NOT NULL DEFAULT false,
    status          TEXT NOT NULL,
    admin_id        BIGINT REFERENCES users (id),
    admin_note      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now())),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT personas_name_nonempty CHECK (char_length(name) > 0),
    CONSTRAINT personas_system_prompt_nonempty CHECK (char_length(system_prompt) > 0),
    CONSTRAINT personas_status_check CHECK (status IN ('private', 'pending', 'approved', 'rejected'))
);

CREATE INDEX IF NOT EXISTS personas_author_idx ON personas (author_user_id);
CREATE INDEX IF NOT EXISTS personas_status_public_idx ON personas (status, is_public) WHERE is_public = true;

-- A user may have a default persona applied to new sessions/tasks.
ALTER TABLE users ADD COLUMN IF NOT EXISTS default_persona_id UUID REFERENCES personas (id) ON DELETE SET NULL;

-- Bots were created by admins with an internal UUID. Self-service binding adds the
-- external iLink bot identifier supplied by the user after scanning their own QR code.
ALTER TABLE bots ADD COLUMN IF NOT EXISTS ilink_bot_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS bots_ilink_bot_id_uq ON bots (ilink_bot_id) WHERE ilink_bot_id IS NOT NULL;

-- Backfill existing bots so the unique partial index is satisfied and lookups work.
UPDATE bots SET ilink_bot_id = bot_uuid::text WHERE ilink_bot_id IS NULL;
